[package]
name = "keepassxc-syncer"
version = "0.1.0"
authors = ["Yukio Usuzumi <anohigisavay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
serde = "1.0"
serde_yaml = "0.8"